name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.5.4
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  modal_progress_hud: ^0.1.3
  google_sign_in: ^5.0.4
  firebase_storage: ^8.1.0
  image_picker: ^0.8.0
  photo_view: ^0.10.3
  google_maps_flutter: ^2.0.6
  location: ^4.1.1
  url_launcher: ^6.0.6
  geolocator: ^7.0.3
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  agora_rtc_engine: ^4.0.2
  permission_handler: ^8.1.1
  provider: ^5.0.0
  http: ^0.13.3
  audioplayers: ^0.19.1
  firebase_messaging: ^10.0.3
  flutter_local_notifications: ^5.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/Ringtone.mp3
